language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: p2FGuHk+iOS76OF5R+3Y4rm1u9Lku3nHlSH59t8pzLr833ZVe/EHKo5prsqxlmcpa9YzpRaVfv92THmEqSG6O8yLRhXYTreScG2js5babMHJWvwvkMqRucFou3Z9zESVtnOPxln3OOicQxtq3ejWAe/5bvVUm45uFE7iqPcYDvLQOON8HxOCIQZAIq8csJUSTAUyRRTvS6NJpRDFe6w9Hw79FvwVTNtlLTHGLcRW9bSxg3AyOF6x9uvMpoHrjtzjVpZxvqLqSG0odYnCTXI3jSzzb25+rer61JLf8O2nf2LwHOhv40uPtE5piFOEg+SVdanclT9QqY9EPboFXoAsA0fFhRMW3WvNfmTLp3LSW+LTNRoM9ZoWtFS3qj7EzwrvpExkDl4ZeZLcMViQCFa7+NkgELLuYcv6zTWSeFFDTvcQDSKteoD+YHKgdx0aWkZEM4mgDcBaaeh2BkdjUaEkijJD5QcVtl57dW4DRHDpbY0BqrWbpGmbApQsG8VJ3b/BblXh3B72SPR7qmVkrmEL4UMVziftjNp9BORxiHzRwDDZSdVD1JwSPHrgC71KV0KBxSgfLxy1JYj6LS2IscKZjh4qM5JCHC/69HytX7DmsQlv982KWU9//2l6KMV6zcw1HHAI4oO4x7/cGXwxhyPhuT1SD6Z6461hPtYludO2moQ=
  app: whispering-lake-86922
  on:
    repo: drichards211/challenge-blog-api
    branch: test-api-endpoints
